FROM golang:1.25 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /logtap-forwarder ./cmd/logtap-forwarder

FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /logtap-forwarder /logtap-forwarder
ENTRYPOINT ["/logtap-forwarder"]
