name: Feature Request
description: Suggest a feature for logtap
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What workflow is painful today?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work? Include CLI examples if applicable.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches did you consider?

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      options:
        - CLI (new flag or subcommand)
        - Receiver (HTTP / write pipeline)
        - Kubernetes (tap / sidecar)
        - Analysis (triage / grep / export)
        - Other
